Repository Gyanthakur/Dev_Profiles, pull requests merged in 2023-10, with the labels that each got.

#3 Update index.html
  index.html
Labels: hactoberfest, hactoberfest-accepted

#8 added my profile
  index.html
Labels: hactoberfest, hactoberfest-accepted, hactoberfest-2023

#10 Add my profile (Hacktober Fest) (Issue #6)
  index.html
Labels: hactoberfest, hactoberfest-accepted, hactoberfest-2023

#18 Update index.html
  index.html
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2023

#19 project-button-fix
  project.html
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2023

#20 Updated index.html
  index.html
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2023

#21 Added my Dev_Profile
  index.html
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2023

#22 Updated project.html
  project.html
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2023

#26 Update index.html
  index.html
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2023

#23 Profile Added
  index.html
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2023

#29 Shaikh mudassir7
  index.html
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2023

#31 Add my profile (Hacktober Fest)
  index.html
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2023

#34 Added Default Profile Image and Added some more padding
  README.md
  default.png
  index.html
  project.html
  style.css
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2023

#24 added my profile in project.html
  project.html
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2023

#39 Added profile
  index.html
  project.html
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2023

#41 feat: improve site ui theme and overall aesthetics
  index.html
  style.css
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2023

#51 Added dark mode to website
  index.html
  script.js
  style.css
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2023

#53 added my project
  project.html
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2023

#50 Added my profile and fixed the position of footer
  index.html
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2023

#55 Added dark mode for projects page
  index.html
  project.html
  style.css
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2023

#57 added profile
  index.html
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2023

#68 Update project.html 21-10-2023
  project.html
Labels: duplicate, hacktoberfest, hacktoberfest-accepted, hacktoberfest-2023

#71 Icon for light mode added
  Moon.png
  Sun.png
  index.html
  project.html
  script.js
  style.css
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2023

#72 profile added
  index.html
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2023

#76 Adding my profile
  index.html
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2023

#81 Add My Profile
  index.html
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2023

#87 Changed theme
  .vscode/settings.json
  style.css
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2023

#88 Added social media icon in footer section
  index.html
  style.css
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2023

#92 Update index.html
  index.html
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2023

#94 Added Card and fixed footer Design
  index.html
  style.css
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2023

#93 Update index.html
  index.html
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2023
