Repository Gyanthakur/Dev_Profiles, pull requests merged in 2024-10, with the labels that each got.

#103 Update greetings.yml
  .github/workflows/greetings.yml
Labels: hacktoberfest, hacktoberfest-accepted, hactoberfest2024

#104 Add Tanvi's Profile and Project
  index.html
  project.html
Labels: hacktoberfest, hacktoberfest-accepted, hactoberfest2024

#105 Update index.html and project.html
  index.html
  project.html
Labels: hacktoberfest, hacktoberfest-accepted, hactoberfest2024

#108 Improve the toggle and responsiveness in the page
  index.html
  project.html
  script.js
  style.css
Labels: hacktoberfest, hacktoberfest-accepted, hactoberfest2024

#109 add: Atik Vohra Profile
  index.html
  project.html
Labels: hacktoberfest, hacktoberfest-accepted, hactoberfest2024

#114 added my profile
  index.html
Labels: hacktoberfest, hacktoberfest-accepted, hactoberfest2024

#127 Added hover effect on footer
  style.css
Labels: hacktoberfest, hacktoberfest-accepted, hactoberfest2024

#128 Fixes Issue #116
  script.js
  style.css
Labels: hacktoberfest, hacktoberfest-accepted, hactoberfest2024

#136 implemented search functionality in profiles section
  .DS_Store
  script.js
Labels: hacktoberfest, hacktoberfest-accepted, hactoberfest2024

#133 issues fixed
  .hintrc
  index.html
Labels: hacktoberfest, hacktoberfest-accepted, hactoberfest2024

#143 X icon fixed
  index.html
Labels: hacktoberfest, hacktoberfest-accepted, hactoberfest2024

#148 fix: light mode toggle now changes background in /projects.html (#146)
  index.html
  project.html
Labels: hacktoberfest, hacktoberfest-accepted, hactoberfest2024

#154 Update index.html
  index.html
  project.html
Labels: hacktoberfest, hacktoberfest-accepted, hactoberfest2024

#160 Update auto-label.yaml
  .github/workflows/auto-label.yaml
Labels: hacktoberfest, hacktoberfest-accepted, hactoberfest2024

#150 feat: Add complete About page with project details as per project (#142)
  about-us.html
  index.html
  project.html
  script.js
  style.css
Labels: hacktoberfest, hacktoberfest-accepted, hactoberfest2024

#144 Update project.html
  index.html
  project.html
Labels: hacktoberfest, hacktoberfest-accepted, hactoberfest2024

#161 Added My Profile and Project
  index.html
  project.html
Labels: hacktoberfest, hacktoberfest-accepted, hactoberfest2024

#178 Hover- effect added: ref to issue #195
  style.css
Labels: hacktoberfest, hacktoberfest-accepted, Hactoberfest

#181 Update autoAssign.yml
  .github/workflows/autoAssign.yml
Labels: Hactoberfest_2024, Hactoberfest-accepted, Hactoberfest

#190 Update greetings.yml
  .github/workflows/greetings.yml
Labels: Hactoberfest_2024, Hactoberfest-accepted, Hactoberfest

#195 Update index.html
  index.html
Labels: Hactoberfest_2024, Hactoberfest-accepted, Hactoberfest

#201 Changed the title of the header from looking as a link
  style.css
Labels: hacktoberfest-accepted

#203 Update greetings.yml
  .github/workflows/greetings.yml
Labels: Hactoberfest_2024, Hactoberfest-accepted, Hactoberfest

#208 Update README.md
  README.md
Labels: Hactoberfest_2024, Hactoberfest-accepted, Hactoberfest

#210 Update greetings.yml
  .github/workflows/greetings.yml
Labels: Hactoberfest_2024, Hactoberfest-accepted, Hactoberfest

#214 Fix some ui related issues in about-us.html
  about-us.html
  style.css
Labels: hacktoberfest-accepted, hactoberfest2024, Hactoberfest_2024

#217 Update autoAssign.yml
  .github/workflows/autoAssign.yml
Labels: Hactoberfest_2024, Hactoberfest-accepted, Hactoberfest

#215 added scroll to top button to all the pages
  about-us.html
  index.html
  project.html
  script.js
  style.css
Labels: hacktoberfest-accepted, hactoberfest2024, Hactoberfest_2024, Hactoberfest, Hacktoberfest_2024

#224 Update greetings.yml
  .github/workflows/greetings.yml
Labels: Hactoberfest_2024, Hactoberfest-accepted, Hactoberfest

#231 Update autoAssign.yml
  .github/workflows/autoAssign.yml
Labels: hacktoberfest, hacktoberfest-accepted, Hacktoberfest_2024

#228 dark mode button improved
  about-us.html
  dark.png
  index.html
  light.png
  project.html
  script.js
  style.css
Labels: hacktoberfest, hacktoberfest-accepted, Hacktoberfest_2024

#233 feat(ui): Enhanced ui in Profile Fixes:#232
  style.css
Labels: hacktoberfest, hacktoberfest-accepted, Hacktoberfest_2024

#221 Added my profile (Pavan Narendra)
  index.html
  style.css
Labels: hacktoberfest-accepted, Hacktoberfest-2024, Hacktoberfest_2024

#238 feat: add contact page for user support
  about-us.html
  contact-us.html
  index.html
  project.html
  script.js
  style.css
Labels: hacktoberfest, hacktoberfest-accepted, Hacktoberfest_2024

#235 Added My Profile
  index.html
Labels: hacktoberfest, hacktoberfest-accepted, Hacktoberfest_2024

#234 Border is added to projects and formatted
  project.html
Labels: hacktoberfest, hacktoberfest-accepted, Hacktoberfest_2024

#243 Added My Project
  index.html
  project.html
Labels: hacktoberfest, hacktoberfest-accepted, Hacktoberfest_2024

#225 Update index.html
  index.html
Labels: hacktoberfest-accepted, Hacktoberfest-2024, Hacktoberfest_2024

#245 Adding up profile
  index.html
  style.css
Labels: hacktoberfest, hacktoberfest-accepted, Hacktoberfest_2024

#246 header redesigned
  about-us.html
  contact-us.html
  index.html
  project.html
  style.css
Labels: hacktoberfest, hacktoberfest-accepted, Hacktoberfest_2024

#257 scroll down progress bar added
  about-us.html
  contact-us.html
  index.html
  project.html
  script.js
  style.css
Labels: hacktoberfest, hacktoberfest-accepted, Hacktoberfest_2024

#259 Updated CONTRIBUTING.md
  CONTRIBUTING.md
Labels: hacktoberfest, hacktoberfest-accepted, Hacktoberfest_2024

#261 Update project.html
  project.html
Labels: hacktoberfest, hacktoberfest-accepted, Hacktoberfest_2024

#253 NAVBAR CSS
  index.html
  script.js
  style.css
Labels: hacktoberfest, hacktoberfest-accepted, Hacktoberfest_2024

#265 #255 Updated the old twitter logo to X
  about-us.html
  contact-us.html
  project.html
Labels: hacktoberfest, hacktoberfest-accepted, Hacktoberfest_2024

#264 Added my profile
  gratisography-cyber-kitty-800x525.jpg
  index.html
Labels: hacktoberfest, hacktoberfest-accepted, Hacktoberfest_2024

#273 hover bug fixed
  style.css
Labels: hacktoberfest, hacktoberfest-accepted, Hacktoberfest_2024

#277 default image is change and code formatted
  default.png
  index.html
Labels: hacktoberfest, hacktoberfest-accepted, Hacktoberfest_2024

#283 Improve responsiveness of Contact Us page
  about-us.html
  contact-us.html
  index.html
  project.html
  style.css
Labels: hacktoberfest, hacktoberfest-accepted, Hacktoberfest_2024

#282 Profie added
  index.html
Labels: hacktoberfest, hacktoberfest-accepted, Hacktoberfest_2024

#276 added new project
  project.html
Labels: hacktoberfest, hacktoberfest-accepted, Hacktoberfest_2024

#285 Profile Added
  index.html
Labels: hacktoberfest, hacktoberfest-accepted, Hacktoberfest_2024

#294 nav links bug fixed
  style.css
Labels: hacktoberfest, hacktoberfest-accepted, Hacktoberfest_2024

#286 Added new profile
  index.html
Labels: hacktoberfest, hacktoberfest-accepted, Hacktoberfest_2024

#292 Added AOS animations and alphabetic sorting to profiles
  index.html
  index.js
  script.js
  style.css
Labels: hacktoberfest, hacktoberfest-accepted, Hacktoberfest_2024

#298 profile added
  index.html
Labels: hacktoberfest, hacktoberfest-accepted, Hacktoberfest_2024

#299 Enhanced the UI of the contact us page.
  contact-us.html
  script.js
  style.css
Labels: hacktoberfest, hacktoberfest-accepted, Hacktoberfest_2024

#302 Card border bug fixed
  style.css
Labels: hacktoberfest, hacktoberfest-accepted, Hacktoberfest_2024

#280 Added new profile
  project.html
Labels: hacktoberfest, hacktoberfest-accepted, Hacktoberfest_2024

#303 Added my profile without touching anything else
  index.html
Labels: hacktoberfest, hacktoberfest-accepted, Hacktoberfest_2024

#305 scroll bug fixed
  index.html
Labels: hacktoberfest, hacktoberfest-accepted, Hacktoberfest_2024

#312 Added my project without touching anything else
  project.html
Labels: hacktoberfest, hacktoberfest-accepted, Hacktoberfest_2024

#310 (add): Profile for Aayush Talreja
  index.html
Labels: hacktoberfest, hacktoberfest-accepted, Hacktoberfest_2024

#316 profiles are sorted
  project.html
Labels: hacktoberfest, hacktoberfest-accepted, Hacktoberfest_2024

#314 updated project.html
  project.html
Labels: hacktoberfest, hacktoberfest-accepted, Hacktoberfest_2024

#318 Contributer
  hacktoberpic.jpeg
  index.html
Labels: hacktoberfest, hacktoberfest-accepted, Hacktoberfest_2024

#319 fix: fixed card update issue while mode switch
  style.css
Labels: hacktoberfest, hacktoberfest-accepted, Hacktoberfest_2024

#321 Updated project card layout
  project.html
  style.css
Labels: hacktoberfest, hacktoberfest-accepted, Hacktoberfest_2024
